const searchData = {
  data: {
    results: [
      {
        id: 654959,
        title: "Pasta With Tuna",
        image: "https://spoonacular.com/recipeImages/654959-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 511728,
        title: "Pasta Margherita",
        image: "https://spoonacular.com/recipeImages/511728-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 654812,
        title: "Pasta and Seafood",
        image: "https://spoonacular.com/recipeImages/654812-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 654857,
        title: "Pasta On The Border",
        image: "https://spoonacular.com/recipeImages/654857-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 654883,
        title: "Pasta Vegetable Soup",
        image: "https://spoonacular.com/recipeImages/654883-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 654928,
        title: "Pasta With Italian Sausage",
        image: "https://spoonacular.com/recipeImages/654928-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 654926,
        title: "Pasta With Gorgonzola Sauce",
        image: "https://spoonacular.com/recipeImages/654926-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 654944,
        title: "Pasta With Salmon Cream Sauce",
        image: "https://spoonacular.com/recipeImages/654944-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 654905,
        title: "Pasta With Chickpeas and Kale",
        image: "https://spoonacular.com/recipeImages/654905-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 654901,
        title: "Pasta With Chicken and Broccoli",
        image: "https://spoonacular.com/recipeImages/654901-312x231.jpg",
        imageType: "jpg",
      },
    ],
    offset: 0,
    number: 10,
    totalResults: 223,
  },
};

const recipeDetails = {
  data: {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 16,
    gaps: "no",
    lowFodmap: false,
    aggregateLikes: 2,
    spoonacularScore: 44.0,
    healthScore: 10.0,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 235.0,
    extendedIngredients: [
      {
        id: 6172,
        aisle: "Canned and Jarred",
        image: "chicken-broth.png",
        consistency: "liquid",
        name: "chicken stock",
        nameClean: "chicken stock",
        original: "8 cups chicken stock",
        originalName: "chicken stock",
        amount: 8.0,
        unit: "cups",
        meta: [],
        measures: {
          us: {
            amount: 8.0,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 1.893,
            unitShort: "l",
            unitLong: "liters",
          },
        },
      },
      {
        id: 1001,
        aisle: "Milk, Eggs, Other Dairy",
        image: "butter-sliced.jpg",
        consistency: "solid",
        name: "butter",
        nameClean: "butter",
        original: "1/4 cup butter",
        originalName: "butter",
        amount: 0.25,
        unit: "cup",
        meta: [],
        measures: {
          us: {
            amount: 0.25,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 59.147,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 1034053,
        aisle: "Oil, Vinegar, Salad Dressing",
        image: "olive-oil.jpg",
        consistency: "liquid",
        name: "extra virgin olive oil",
        nameClean: "extra virgin olive oil",
        original: "2 tablespoons extra virgin olive oil",
        originalName: "extra virgin olive oil",
        amount: 2.0,
        unit: "tablespoons",
        meta: [],
        measures: {
          us: {
            amount: 2.0,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
          metric: {
            amount: 2.0,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
        },
      },
      {
        id: 11282,
        aisle: "Produce",
        image: "brown-onion.png",
        consistency: "solid",
        name: "onions",
        nameClean: "onion",
        original: "2 cups finely chopped onions",
        originalName: "finely chopped onions",
        amount: 2.0,
        unit: "cups",
        meta: ["finely chopped"],
        measures: {
          us: {
            amount: 2.0,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 473.176,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 11215,
        aisle: "Produce",
        image: "garlic.png",
        consistency: "solid",
        name: "garlic cloves",
        nameClean: "garlic",
        original: "2 garlic cloves, minced",
        originalName: "garlic cloves, minced",
        amount: 2.0,
        unit: "",
        meta: ["minced"],
        measures: {
          us: {
            amount: 2.0,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 2.0,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 10020052,
        aisle: "Pasta and Rice",
        image: "arborio-rice.png",
        consistency: "solid",
        name: "arborio rice",
        nameClean: "risotto rice",
        original: "1 1/2 cups Arborio Rice",
        originalName: "Arborio Rice",
        amount: 1.5,
        unit: "cups",
        meta: [],
        measures: {
          us: {
            amount: 1.5,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 354.882,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 14106,
        aisle: "Alcoholic Beverages",
        image: "white-wine.jpg",
        consistency: "liquid",
        name: "dry white wine",
        nameClean: "dry white wine",
        original: "2/3 cup dry white wine",
        originalName: "dry white wine",
        amount: 0.6666666666666666,
        unit: "cup",
        meta: ["dry white"],
        measures: {
          us: {
            amount: 0.667,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 157.725,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 11304,
        aisle: "Produce",
        image: "peas.jpg",
        consistency: "solid",
        name: "peas",
        nameClean: "petite peas",
        original: "3/4 cup peas",
        originalName: "peas",
        amount: 0.75,
        unit: "cup",
        meta: [],
        measures: {
          us: {
            amount: 0.75,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 177.441,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 1033,
        aisle: "Cheese",
        image: "parmesan.jpg",
        consistency: "solid",
        name: "parmesan",
        nameClean: "parmesan",
        original: "2/3 cup grated Parmesan",
        originalName: "grated Parmesan",
        amount: 0.6666666666666666,
        unit: "cup",
        meta: ["grated"],
        measures: {
          us: {
            amount: 0.667,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 157.725,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 2004,
        aisle: "Spices and Seasonings",
        image: "bay-leaves.jpg",
        consistency: "solid",
        name: "bay leaf",
        nameClean: "bay leaves",
        original: "1 bay leaf",
        originalName: "bay leaf",
        amount: 1.0,
        unit: "",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 1.0,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 1102047,
        aisle: "Spices and Seasonings",
        image: "salt-and-pepper.jpg",
        consistency: "solid",
        name: "salt and pepper",
        nameClean: "salt and pepper",
        original: "Salt and pepper",
        originalName: "Salt and pepper",
        amount: 1.0,
        unit: "serving",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "serving",
            unitLong: "serving",
          },
          metric: {
            amount: 1.0,
            unitShort: "serving",
            unitLong: "serving",
          },
        },
      },
    ],
    id: 658384,
    title: "Risotto With Fresh Peas",
    readyInMinutes: 45,
    servings: 6,
    sourceUrl:
      "https://www.foodista.com/recipe/RZ8Y824Q/risotto-with-fresh-peas",
    image: "https://spoonacular.com/recipeImages/658384-556x370.jpg",
    imageType: "jpg",
    summary:
      'Risotto With Fresh Peas might be a good recipe to expand your main course collection. One portion of this dish contains about <b>17g of protein</b>, <b>19g of fat</b>, and a total of <b>506 calories</b>. This recipe serves 6 and costs $2.35 per serving. 2 people have tried and liked this recipe. If you have bay leaf, garlic cloves, extra virgin olive oil, and a few other ingredients on hand, you can make it. It is a good option if you\'re following a <b>gluten free</b> diet. From preparation to the plate, this recipe takes about <b>about 45 minutes</b>. This recipe is typical of Mediterranean cuisine. It is brought to you by Foodista. With a spoonacular <b>score of 42%</b>, this dish is pretty good. Similar recipes include <a href="https://spoonacular.com/recipes/risotto-with-fresh-peas-and-asparagus-18180">Risotto With Fresh Peas And Asparagus</a>, <a href="https://spoonacular.com/recipes/risotto-bianco-with-enoki-and-fresh-peas-387660">Risotto Bianco with Enoki and Fresh Peas</a>, and <a href="https://spoonacular.com/recipes/farmers-market-risotto-with-spring-onion-fresh-peas-and-mint-670152">Farmers’ Market Risotto with Spring Onion, Fresh Peas, and Mint</a>.',
    cuisines: ["Mediterranean", "Italian", "European"],
    dishTypes: ["side dish", "lunch", "main course", "main dish", "dinner"],
    diets: ["gluten free"],
    occasions: [],
    winePairing: {
      pairedWines: ["chianti", "trebbiano", "verdicchio"],
      pairingText:
        "Chianti, Trebbiano, and Verdicchio are great choices for Risotto. Italians know food and they know wine. Trebbiano and Verdicchio are Italian white wines that pair well with fish and white meat, while Chianti is a great Italian red for heavier, bolder dishes. One wine you could try is Tenuta di Arceno Stradan al Sasso Chianti Classico Gran Selezione. It has 4.3 out of 5 stars and a bottle costs about 50 dollars.",
      productMatches: [
        {
          id: 493538,
          title:
            "Tenuta di Arceno Strada al Sasso Chianti Classico Gran Selezione",
          description:
            "2015 was the perfect warm vintage- not too hot, just right. The nose immediately releases tones of honeysuckle and strawberry jam, finishing with a herbal tone of rosemary and cypress. On the palate, the power of this wine impresses. There is an explosion of flavors, all framed tightly by firm bright acids. Flavors are dominated by tart cranberries and raspberries, giving way to the ever-elusive lush blueberry tones. The finish is dominated by vanilla bean with lingering black pepper and orange peel. This is an exciting year for Sangiovese and has the potential to age 15–20 years.",
          price: "$49.99",
          imageUrl: "https://spoonacular.com/productImages/493538-312x231.jpg",
          averageRating: 0.86,
          ratingCount: 9.0,
          score: 0.8242857142857143,
          link: "https://click.linksynergy.com/deeplink?id=*QCiIS6t4gA&mid=2025&murl=https%3A%2F%2Fwww.wine.com%2Fproduct%2Ftenuta-di-arceno-strada-al-sasso-chianti-classico-gran-selezione-2016%2F581329",
        },
      ],
    },
    instructions:
      "Melt butter in heavy large saucepan over medium heat, add evo, bay leaf and onions.  Season with salt and pepper.  Cook until onions are translucent.  Add minced garlic.  Saute until tender, roughly 8 minutes.\nStir in the rice and toast it for a few minutes.  Add wine, cook until the liquid is absorbed, stirring often, about 2 minutes.  Add 1 cup of HOT chicken broth at a time, making sure the liquid is absorbed, stirring often.  This process should be done over medium low heat and will take about 28 minutes.  Add 1 cup of chicken broth roughly every 3 minutes.  Cook the rice until tender and mixture is creamy.\nContinue to stir in the peas, Parmesan, salt and pepper to taste.  Cook until the mixture has absorbed all the liquid.  It will double in size. Let cool and don't eat it all.  For some reason, the mixture doesn't last long around my house.",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Melt butter in heavy large saucepan over medium heat, add evo, bay leaf and onions.  Season with salt and pepper.  Cook until onions are translucent.",
            ingredients: [
              {
                id: 1102047,
                name: "salt and pepper",
                localizedName: "salt and pepper",
                image: "salt-and-pepper.jpg",
              },
              {
                id: 2004,
                name: "bay leaves",
                localizedName: "bay leaves",
                image: "bay-leaves.jpg",
              },
              {
                id: 1001,
                name: "butter",
                localizedName: "butter",
                image: "butter-sliced.jpg",
              },
              {
                id: 11282,
                name: "onion",
                localizedName: "onion",
                image: "brown-onion.png",
              },
            ],
            equipment: [
              {
                id: 404669,
                name: "sauce pan",
                localizedName: "sauce pan",
                image: "sauce-pan.jpg",
              },
            ],
          },
          {
            number: 2,
            step: "Add minced garlic.",
            ingredients: [
              {
                id: 0,
                name: "minced garlic",
                localizedName: "minced garlic",
                image: "garlic.png",
              },
            ],
            equipment: [],
          },
          {
            number: 3,
            step: "Saute until tender, roughly 8 minutes.",
            ingredients: [],
            equipment: [],
            length: {
              number: 8,
              unit: "minutes",
            },
          },
          {
            number: 4,
            step: "Stir in the rice and toast it for a few minutes.",
            ingredients: [
              {
                id: 18070,
                name: "toast",
                localizedName: "toast",
                image: "toast",
              },
              {
                id: 20444,
                name: "rice",
                localizedName: "rice",
                image: "uncooked-white-rice.png",
              },
            ],
            equipment: [],
          },
          {
            number: 5,
            step: "Add wine, cook until the liquid is absorbed, stirring often, about 2 minutes.",
            ingredients: [
              {
                id: 14084,
                name: "wine",
                localizedName: "wine",
                image: "red-wine.jpg",
              },
            ],
            equipment: [],
            length: {
              number: 2,
              unit: "minutes",
            },
          },
          {
            number: 6,
            step: "Add 1 cup of HOT chicken broth at a time, making sure the liquid is absorbed, stirring often.  This process should be done over medium low heat and will take about 28 minutes.",
            ingredients: [
              {
                id: 6194,
                name: "chicken broth",
                localizedName: "chicken broth",
                image: "chicken-broth.png",
              },
            ],
            equipment: [],
            length: {
              number: 28,
              unit: "minutes",
            },
          },
          {
            number: 7,
            step: "Add 1 cup of chicken broth roughly every 3 minutes.  Cook the rice until tender and mixture is creamy.",
            ingredients: [
              {
                id: 6194,
                name: "chicken broth",
                localizedName: "chicken broth",
                image: "chicken-broth.png",
              },
              {
                id: 20444,
                name: "rice",
                localizedName: "rice",
                image: "uncooked-white-rice.png",
              },
            ],
            equipment: [],
            length: {
              number: 3,
              unit: "minutes",
            },
          },
          {
            number: 8,
            step: "Continue to stir in the peas, Parmesan, salt and pepper to taste.  Cook until the mixture has absorbed all the liquid.  It will double in size.",
            ingredients: [
              {
                id: 1102047,
                name: "salt and pepper",
                localizedName: "salt and pepper",
                image: "salt-and-pepper.jpg",
              },
              {
                id: 1033,
                name: "parmesan",
                localizedName: "parmesan",
                image: "parmesan.jpg",
              },
              {
                id: 11304,
                name: "peas",
                localizedName: "peas",
                image: "peas.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 9,
            step: "Let cool and don't eat it all.  For some reason, the mixture doesn't last long around my house.",
            ingredients: [],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/risotto-with-fresh-peas-658384",
  },
};

const moreData = {
  data: {
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 4,
    gaps: "no",
    lowFodmap: false,
    preparationMinutes: 20,
    cookingMinutes: 225,
    aggregateLikes: 0,
    spoonacularScore: 12,
    healthScore: 1,
    creditsText: "maplewoodroad",
    sourceName: "Maplewood Road",
    pricePerServing: 387.53,
    extendedIngredients: [
      {
        id: 11282,
        aisle: "Produce",
        image: "brown-onion.png",
        consistency: "solid",
        name: "onion",
        nameClean: "onion",
        original: "1 onion, chopped (one cup)",
        originalName: "onion, chopped (one cup)",
        amount: 1,
        unit: "",
        meta: ["chopped", "(one cup)"],
        measures: {
          us: {
            amount: 1,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 1,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 10111143,
        aisle: "Produce",
        image: "celery.jpg",
        consistency: "solid",
        name: "celery stalks",
        nameClean: "celery sticks",
        original: "2 celery stalks, chopped (one cup)",
        originalName: "celery stalks, chopped (one cup)",
        amount: 2,
        unit: "",
        meta: ["chopped", "(one cup)"],
        measures: {
          us: {
            amount: 2,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 2,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 11124,
        aisle: "Produce",
        image: "sliced-carrot.png",
        consistency: "solid",
        name: "carrots",
        nameClean: "carrot",
        original: "2 carrots, chopped (one cup)",
        originalName: "carrots, chopped (one cup)",
        amount: 2,
        unit: "",
        meta: ["chopped", "(one cup)"],
        measures: {
          us: {
            amount: 2,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 2,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 10211215,
        aisle: "Produce",
        image: "garlic.jpg",
        consistency: "solid",
        name: "garlic cloves",
        nameClean: "whole garlic cloves",
        original: "2 garlic cloves, finely chopped",
        originalName: "garlic cloves, finely chopped",
        amount: 2,
        unit: "",
        meta: ["finely chopped"],
        measures: {
          us: {
            amount: 2,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 2,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 1001,
        aisle: "Milk, Eggs, Other Dairy",
        image: "butter-sliced.jpg",
        consistency: "solid",
        name: "butter",
        nameClean: "butter",
        original: "2 Tbsp butter",
        originalName: "butter",
        amount: 2,
        unit: "Tbsp",
        meta: [],
        measures: {
          us: {
            amount: 2,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
          metric: {
            amount: 2,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
        },
      },
      {
        id: 4053,
        aisle: "Oil, Vinegar, Salad Dressing",
        image: "olive-oil.jpg",
        consistency: "liquid",
        name: "olive oil",
        nameClean: "olive oil",
        original: "1 Tbsp olive oil",
        originalName: "olive oil",
        amount: 1,
        unit: "Tbsp",
        meta: [],
        measures: {
          us: {
            amount: 1,
            unitShort: "Tbsp",
            unitLong: "Tbsp",
          },
          metric: {
            amount: 1,
            unitShort: "Tbsp",
            unitLong: "Tbsp",
          },
        },
      },
      {
        id: 14106,
        aisle: "Alcoholic Beverages",
        image: "white-wine.jpg",
        consistency: "liquid",
        name: "white wine",
        nameClean: "dry white wine",
        original: "1/2 cup white wine",
        originalName: "white wine",
        amount: 0.5,
        unit: "cup",
        meta: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 118.294,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 10411529,
        aisle: "Produce",
        image: "plum-tomatoes.png",
        consistency: "solid",
        name: "plum tomatoes",
        nameClean: "plum tomato",
        original: "28 oz crushed Italian plum tomatoes (canned)",
        originalName: "crushed Italian plum tomatoes (canned)",
        amount: 28,
        unit: "oz",
        meta: ["italian", "canned", "crushed", "()"],
        measures: {
          us: {
            amount: 28,
            unitShort: "oz",
            unitLong: "ounces",
          },
          metric: {
            amount: 793.787,
            unitShort: "g",
            unitLong: "grams",
          },
        },
      },
      {
        id: 6170,
        aisle: "Canned and Jarred",
        image: "beef-broth.png",
        consistency: "liquid",
        name: "beef stock",
        nameClean: "beef stock",
        original: "3 cups beef stock",
        originalName: "beef stock",
        amount: 3,
        unit: "cups",
        meta: [],
        measures: {
          us: {
            amount: 3,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 709.764,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 1053,
        aisle: "Milk, Eggs, Other Dairy",
        image: "fluid-cream.jpg",
        consistency: "liquid",
        name: "heavy cream",
        nameClean: "cream",
        original: "1/2 cup heavy cream",
        originalName: "heavy cream",
        amount: 0.5,
        unit: "cup",
        meta: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 118.294,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 10410123,
        aisle: "Meat",
        image: "pancetta.png",
        consistency: "solid",
        name: "pancetta",
        nameClean: "pancetta",
        original: "4 oz pancetta, chopped",
        originalName: "pancetta, chopped",
        amount: 4,
        unit: "oz",
        meta: ["chopped"],
        measures: {
          us: {
            amount: 4,
            unitShort: "oz",
            unitLong: "ounces",
          },
          metric: {
            amount: 113.398,
            unitShort: "g",
            unitLong: "grams",
          },
        },
      },
      {
        id: 10023572,
        aisle: "Meat",
        image: "fresh-ground-beef.jpg",
        consistency: "solid",
        name: "ground beef",
        nameClean: "ground chuck",
        original: "9 oz ground beef",
        originalName: "ground beef",
        amount: 9,
        unit: "oz",
        meta: [],
        measures: {
          us: {
            amount: 9,
            unitShort: "oz",
            unitLong: "ounces",
          },
          metric: {
            amount: 255.146,
            unitShort: "g",
            unitLong: "grams",
          },
        },
      },
      {
        id: 10219,
        aisle: "Meat",
        image: "meat-ground.jpg",
        consistency: "solid",
        name: "ground pork",
        nameClean: "ground pork",
        original: "9 oz ground pork",
        originalName: "ground pork",
        amount: 9,
        unit: "oz",
        meta: [],
        measures: {
          us: {
            amount: 9,
            unitShort: "oz",
            unitLong: "ounces",
          },
          metric: {
            amount: 255.146,
            unitShort: "g",
            unitLong: "grams",
          },
        },
      },
      {
        id: 1102047,
        aisle: "Spices and Seasonings",
        image: "salt-and-pepper.jpg",
        consistency: "solid",
        name: "salt & pepper",
        nameClean: "salt and pepper",
        original: "Salt &amp; pepper",
        originalName: "Salt & pepper",
        amount: 1,
        unit: "serving",
        meta: [],
        measures: {
          us: {
            amount: 1,
            unitShort: "serving",
            unitLong: "serving",
          },
          metric: {
            amount: 1,
            unitShort: "serving",
            unitLong: "serving",
          },
        },
      },
      {
        id: 1001,
        aisle: "Milk, Eggs, Other Dairy",
        image: "butter-sliced.jpg",
        consistency: "solid",
        name: "butter",
        nameClean: "butter",
        original: "1/4 cup butter",
        originalName: "butter",
        amount: 0.25,
        unit: "cup",
        meta: [],
        measures: {
          us: {
            amount: 0.25,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 59.147,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 20081,
        aisle: "Baking",
        image: "flour.png",
        consistency: "solid",
        name: "flour",
        nameClean: "wheat flour",
        original: "1/2 cup flour",
        originalName: "flour",
        amount: 0.5,
        unit: "cup",
        meta: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 118.294,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 1077,
        aisle: "Milk, Eggs, Other Dairy",
        image: "milk.png",
        consistency: "liquid",
        name: "milk",
        nameClean: "milk",
        original: "4 cups hot milk",
        originalName: "hot milk",
        amount: 4,
        unit: "cups",
        meta: ["hot"],
        measures: {
          us: {
            amount: 4,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 946.352,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 10620421,
        aisle: "Pasta and Rice",
        image: "lasagna-noodles.jpg",
        consistency: "solid",
        name: "lasagne sheets",
        nameClean: "cooked lasagne noodles",
        original: "12 pre-cooked lasagne sheets",
        originalName: "pre-cooked lasagne sheets",
        amount: 12,
        unit: "",
        meta: ["pre-cooked"],
        measures: {
          us: {
            amount: 12,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 12,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 6170,
        aisle: "Canned and Jarred",
        image: "beef-broth.png",
        consistency: "liquid",
        name: "beef stock",
        nameClean: "beef stock",
        original: "1/2 cup beef stock",
        originalName: "beef stock",
        amount: 0.5,
        unit: "cup",
        meta: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 118.294,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 1033,
        aisle: "Cheese",
        image: "parmesan.jpg",
        consistency: "solid",
        name: "parmesan cheese",
        nameClean: "parmesan",
        original: "1 cup Parmesan cheese, freshly grated",
        originalName: "Parmesan cheese, freshly grated",
        amount: 1,
        unit: "cup",
        meta: ["freshly grated"],
        measures: {
          us: {
            amount: 1,
            unitShort: "cup",
            unitLong: "cup",
          },
          metric: {
            amount: 236.588,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
    ],
    id: 1697743,
    title: "Lasagne al Forno with Bolognese and Béchamel Sauce",
    author: "maplewoodroad",
    readyInMinutes: 245,
    servings: 6,
    sourceUrl: "https://maplewoodroad.com/lasagne-al-forno/",
    image: "https://spoonacular.com/recipeImages/1697743-556x370.jpg",
    imageType: "jpg",
    summary:
      'Lasagne al Forno with Bolognese and Béchamel Sauce is a Mediterranean hor d\'oeuvre. This recipe serves 6 and costs $3.88 per serving. One portion of this dish contains approximately <b>1g of protein</b>, <b>1g of fat</b>, and a total of <b>140 calories</b>. From preparation to the plate, this recipe takes roughly <b>4 hours and 5 minutes</b>. Head to the store and pick up plum tomatoes, butter, salt & pepper, and a few other things to make it today. It is brought to you by spoonacular user <a href="/profile/maplewoodroad">maplewoodroad</a>. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/savory-sundays-lasagna-bolognese-with-bechamel-sauce-566187">Savory Sundays: Lasagna Bolognese with Bechamel Sauce</a>, <a href="https://spoonacular.com/recipes/lasagne-al-forno-697263">Lasagne al Forno</a>, and <a href="https://spoonacular.com/recipes/lasagne-bolognese-157195">Lasagne Bolognese</a>.',
    cuisines: ["Mediterranean", "Italian", "European"],
    dishTypes: [
      "antipasti",
      "starter",
      "snack",
      "appetizer",
      "antipasto",
      "hor d'oeuvre",
    ],
    diets: [],
    occasions: [],
    winePairing: {
      pairedWines: ["chianti", "montepulciano", "sangiovese"],
      pairingText:
        "Lasagne works really well with Chianti, Montepulciano, and Sangiovese. Lasagna pairs well with medium-bodied red wine with higher acidity. Sangiovese, Montepulciano, and Chianti all fit the bill. The Felsina Berardenga Chianti Classico ( Half-bottle) with a 4.2 out of 5 star rating seems like a good match. It costs about 13 dollars per bottle.",
      productMatches: [
        {
          id: 444478,
          title: "Felsina Berardenga Chianti Classico ( Half-bottle)",
          description:
            '"Shows fresh berry, with hints of flowers, fresh herbs and chocolate. Full-bodied, with a fresh palate, well-integrated tannins and a balanced finish. Lots of cherry and light spice. Best after 2003."-Wine Spectator',
          price: "$12.99",
          imageUrl: "https://spoonacular.com/productImages/444478-312x231.jpg",
          averageRating: 0.8400000000000001,
          ratingCount: 24,
          score: 0.8263013698630137,
          link: "https://click.linksynergy.com/deeplink?id=*QCiIS6t4gA&mid=2025&murl=https%3A%2F%2Fwww.wine.com%2Fproduct%2Ffelsina-berardenga-chianti-classico-375ml-half-bottle-2009%2F114885",
        },
      ],
    },
    instructions:
      "Instructions\n\n \n\nBolognese Sauce:\n\nHeat butter and oil in a large saucepan until sizzling.\n\nThen add all the vegetables and pancetta, and stir occasionally for 10 minutes. You want the vegetables to soften up a bit.\n\nLower the heat a bit and add the meats.  Gently cook them by stirring and breaking up any clumps.  After about 10 minutes, season with salt & pepper.\n\nAdd the wine and stir for about 5 minutes until reduced.  You may have to turn up the heat a little bit for this step. \n\nNow add the crushed tomatoes and about a cup of beef stock and bring to a boil.\n\nNext, lower the heat to a gentle simmer, and over the next two hours, occasionally stir and add beef stock as needed to keep the ragu from sticking to the pan.\n\nAdd heavy cream, stir very well, and let simmer for another 30 minutes.\n\nAdd some more stock to your bolognese (you want the sauce to be pretty runny).\n\nBechamel Sauce:\n\nPreheat oven to 375℉.\n\nCook the lasagne sheets while making the Béchamel, so they’ll be ready.\n\nHeat up the milk in a saucepan.\n\nIn a different saucepan, melt the butter, add flour, and stir for about 2 minutes.\n\nBring to a boil, slowly add the warmed milk a little bit at a time, while whisking vigorously, until the sauce becomes thick and smooth. Season with salt and pepper.\n\nAssemble Lasagne:\n\nIn a greased 9” x 13” baking dish, add about a third of the bolognese, cover with a quarter of the Bechamel, and add four lasagne sheets.\n\nRepeat two more times. \n\n Add remaining Bechamel and sprinkle your Parmesan evenly on top.\n\nBake for about 40-45 minutes and let rest for about 10 minutes before serving.",
    analyzedInstructions: [
      {
        name: "Bolognese Sauce",
        steps: [
          {
            number: 1,
            step: "Heat butter and oil in a large saucepan until sizzling.",
            ingredients: [
              {
                id: 1001,
                name: "butter",
                localizedName: "butter",
                image: "butter-sliced.jpg",
              },
              {
                id: 4582,
                name: "cooking oil",
                localizedName: "cooking oil",
                image: "vegetable-oil.jpg",
              },
            ],
            equipment: [
              {
                id: 404669,
                name: "sauce pan",
                localizedName: "sauce pan",
                image: "sauce-pan.jpg",
              },
            ],
          },
          {
            number: 2,
            step: "Then add all the vegetables and pancetta, and stir occasionally for 10 minutes. You want the vegetables to soften up a bit.",
            ingredients: [
              {
                id: 11583,
                name: "vegetable",
                localizedName: "vegetable",
                image: "mixed-vegetables.png",
              },
              {
                id: 10410123,
                name: "pancetta",
                localizedName: "pancetta",
                image: "pancetta.png",
              },
            ],
            equipment: [],
            length: {
              number: 10,
              unit: "minutes",
            },
          },
          {
            number: 3,
            step: "Lower the heat a bit and add the meats.  Gently cook them by stirring and breaking up any clumps.  After about 10 minutes, season with salt & pepper.",
            ingredients: [
              {
                id: 1102047,
                name: "salt and pepper",
                localizedName: "salt and pepper",
                image: "salt-and-pepper.jpg",
              },
            ],
            equipment: [],
            length: {
              number: 10,
              unit: "minutes",
            },
          },
          {
            number: 4,
            step: "Add the wine and stir for about 5 minutes until reduced.  You may have to turn up the heat a little bit for this step. ",
            ingredients: [
              {
                id: 14084,
                name: "wine",
                localizedName: "wine",
                image: "red-wine.jpg",
              },
            ],
            equipment: [],
            length: {
              number: 5,
              unit: "minutes",
            },
          },
          {
            number: 5,
            step: "Now add the crushed tomatoes and about a cup of beef stock and bring to a boil.",
            ingredients: [
              {
                id: 11693,
                name: "crushed tomatoes",
                localizedName: "crushed tomatoes",
                image: "tomatoes-canned.png",
              },
              {
                id: 6170,
                name: "beef stock",
                localizedName: "beef stock",
                image: "beef-broth.png",
              },
            ],
            equipment: [],
          },
          {
            number: 6,
            step: "Next, lower the heat to a gentle simmer, and over the next two hours, occasionally stir and add beef stock as needed to keep the ragu from sticking to the pan.",
            ingredients: [
              {
                id: 6170,
                name: "beef stock",
                localizedName: "beef stock",
                image: "beef-broth.png",
              },
            ],
            equipment: [
              {
                id: 404645,
                name: "frying pan",
                localizedName: "frying pan",
                image: "pan.png",
              },
            ],
            length: {
              number: 120,
              unit: "minutes",
            },
          },
          {
            number: 7,
            step: "Add heavy cream, stir very well, and let simmer for another 30 minutes.",
            ingredients: [
              {
                id: 1053,
                name: "heavy cream",
                localizedName: "heavy cream",
                image: "fluid-cream.jpg",
              },
            ],
            equipment: [],
            length: {
              number: 30,
              unit: "minutes",
            },
          },
          {
            number: 8,
            step: "Add some more stock to your bolognese (you want the sauce to be pretty runny).",
            ingredients: [
              {
                id: 0,
                name: "bolognese",
                localizedName: "bolognese",
                image: "tomato-sauce-or-pasta-sauce.jpg",
              },
              {
                id: 0,
                name: "sauce",
                localizedName: "sauce",
                image: "",
              },
              {
                id: 1006615,
                name: "stock",
                localizedName: "stock",
                image: "chicken-broth.png",
              },
            ],
            equipment: [],
          },
        ],
      },
      {
        name: "Bechamel Sauce",
        steps: [
          {
            number: 1,
            step: "Preheat oven to 375℉.",
            ingredients: [],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
              },
            ],
          },
          {
            number: 2,
            step: "Cook the lasagne sheets while making the Béchamel, so they’ll be ready.",
            ingredients: [
              {
                id: 10620420,
                name: "lasagne noodles",
                localizedName: "lasagne noodles",
                image: "lasagna-noodles.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 3,
            step: "Heat up the milk in a saucepan.",
            ingredients: [
              {
                id: 1077,
                name: "milk",
                localizedName: "milk",
                image: "milk.png",
              },
            ],
            equipment: [
              {
                id: 404669,
                name: "sauce pan",
                localizedName: "sauce pan",
                image: "sauce-pan.jpg",
              },
            ],
          },
          {
            number: 4,
            step: "In a different saucepan, melt the butter, add flour, and stir for about 2 minutes.",
            ingredients: [
              {
                id: 1001,
                name: "butter",
                localizedName: "butter",
                image: "butter-sliced.jpg",
              },
              {
                id: 20081,
                name: "all purpose flour",
                localizedName: "all purpose flour",
                image: "flour.png",
              },
            ],
            equipment: [
              {
                id: 404669,
                name: "sauce pan",
                localizedName: "sauce pan",
                image: "sauce-pan.jpg",
              },
            ],
            length: {
              number: 2,
              unit: "minutes",
            },
          },
          {
            number: 5,
            step: "Bring to a boil, slowly add the warmed milk a little bit at a time, while whisking vigorously, until the sauce becomes thick and smooth. Season with salt and pepper.",
            ingredients: [
              {
                id: 1102047,
                name: "salt and pepper",
                localizedName: "salt and pepper",
                image: "salt-and-pepper.jpg",
              },
              {
                id: 0,
                name: "sauce",
                localizedName: "sauce",
                image: "",
              },
              {
                id: 1077,
                name: "milk",
                localizedName: "milk",
                image: "milk.png",
              },
            ],
            equipment: [
              {
                id: 404661,
                name: "whisk",
                localizedName: "whisk",
                image: "whisk.png",
              },
            ],
          },
        ],
      },
      {
        name: "Assemble Lasagne",
        steps: [
          {
            number: 1,
            step: "In a greased 9” x 13” baking dish, add about a third of the bolognese, cover with a quarter of the Bechamel, and add four lasagne sheets.",
            ingredients: [
              {
                id: 10620420,
                name: "lasagne noodles",
                localizedName: "lasagne noodles",
                image: "lasagna-noodles.jpg",
              },
              {
                id: 0,
                name: "bolognese",
                localizedName: "bolognese",
                image: "tomato-sauce-or-pasta-sauce.jpg",
              },
            ],
            equipment: [
              {
                id: 404646,
                name: "baking pan",
                localizedName: "baking pan",
                image: "roasting-pan.jpg",
              },
            ],
          },
          {
            number: 2,
            step: "Repeat two more times. ",
            ingredients: [],
            equipment: [],
          },
          {
            number: 3,
            step: "Add remaining Bechamel and sprinkle your Parmesan evenly on top.",
            ingredients: [
              {
                id: 1033,
                name: "parmesan",
                localizedName: "parmesan",
                image: "parmesan.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 4,
            step: "Bake for about 40-45 minutes and let rest for about 10 minutes before serving.",
            ingredients: [],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
              },
            ],
            length: {
              number: 55,
              unit: "minutes",
            },
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/lasagne-al-forno-with-bolognese-and-bchamel-sauce-1697743",
  },
  status: 200,
  statusText: "",
  headers: {
    "content-type": "application/json",
  },
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false,
    },
    transformRequest: [null],
    transformResponse: [null],
    timeout: 0,
    xsrfCookieName: "XSRF-TOKEN",
    xsrfHeaderName: "X-XSRF-TOKEN",
    maxContentLength: -1,
    maxBodyLength: -1,
    headers: {
      Accept: "application/json, text/plain, */*",
    },
    method: "get",
    url: "https://api.spoonacular.com/recipes/1697743/information?includeNutrition=false&apiKey=c3418aa7875b41dca9f760f502089b64",
  },
  request: {},
};

export { searchData, recipeDetails, moreData };
